README.md

A small change to `README.md` to mention the patterns of WebAssembly modules memory management in [`emscripten`](https://emscripten.org/).
[Embind docs](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management).
[WebIDL binder docs.](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#using-c-classes-in-javascript)

Add example with Emscripten resource management patterns to README.md

---

.github/workflows/build.yml
.github/workflows/pr.yml
README.md
spec.emu

This drops the `const` keyword from `using` declarations to reduce confusion over the fact _BindingPattern_ is disallowed.

Drop 'const' from 'using' declarations

---

README.md
future/using-await-declaration.md
future/using-await-statement.md
future/using-statement.md
future/using-void-declaration.md
spec.emu

Following a [twitter conversation](https://twitter.com/littledan/status/1555619485905784833) with @littledan at the beginning of August, this PR reduces the scope of the Explicit Resource Management proposal to focus specifically on RAII-style `using` declarations.
As a result, the following features are now considered out of scope and would instead be addressed by follow-on proposals:
- Bindingless `using void` declarations.
- Block-style `using` statements.
- Block-style `using await` statements.
- RAII-style `using await` declarations.
Supersedes #86

Reduce proposal scope to only RAII-style 'using' declarations

---

spec.emu

I believe the early error here should only be applied to the using declaration.

Fix UsingDeclaration early error

---

spec.emu

This was first noticed in the Babel PR for `using`: https://github.com/babel/babel/pull/14968#pullrequestreview-1117662244. Rather than introduce additional complexity with a cover grammar, this instead prevents `of` from being considered as a _BindingIdentifier_ in a `for (using ...)`. 
The intent is that the source:
```js
for (using of of [x]) 
```
will be parsed as:
```
for ( using of of [x] )
^^^^^ ^^ ^^ ^^^
|     |  |
|     |  AssignmentExpression->MemberExpression (`of[x]`)
|     |
|     `of` keyword
|
LeftHandSideExpression->Identifier `using`
```
This is to preserve backwards compatibility with existing JS.
Fixes #107

Disallow 'for (using of of ...)'

---

README.md
spec.emu

This removes support for `Symbol.species`, per https://github.com/tc39/proposal-explicit-resource-management/issues/93#issuecomment-1249559013

Remove Symbol.species support

---

README.md
spec.emu

Per the September 2022 plenary, the overloaded `use` method should be split into multiple, distinct methods. These methods are as follows:
- `use(value)` - Adds a disposable resource to the stack.
- If the argument is `null` or `undefined`, it is returned as-is.
- If the argument is not an Object, an error is thrown.
- If the argument does not have a `[Symbol.dispose]()` method, an error is thrown.
- `adopt(value, onDispose)` - Adds a non-disposable resource to the stack with a dispose callback.
- If `onDispose` is not callable, an error is thrown.
- `value` can be any value, including `null` or `undefined`. It will always be tracked.
- When the stack is disposed, the `onDispose` callback will be invoked with `value` as its argument (i.e., `onDispose(value)`).
- `defer(onDispose)` - Adds …

Split 'use' overloads into multiple methods

---

README.md
spec.emu

Adds a `disposed` property that returns a boolean indicating whether the stack has been disposed.
Fixes #113

Adds a 'disposed' property to DisposableStack and AsyncDisposableStack

---

README.md
spec.emu

Changes the auto-bound `dispose` and `disposeAsync` methods/getters into standard methods.

Remove auto-bound 'dispose' and 'disposeAsync' getters

---

spec.emu

This bans the use of `await` as an identifier in a `using` declaration, to ensure forwards compatibility with https://github.com/tc39/proposal-async-explicit-resource-management/. This is necessary because `await` is a valid BindingIdentifier in non-strict-mode code, per [13.1.1 Static Semantics: Early Errors](https://tc39.es/ecma262/#sec-identifiers-static-semantics-early-errors), and `using` declarations are legal in non-strict-mode code.
If we do not explicitly ban `await`, we would be unable to introduce the `using await` declaration due to the syntactic ambiguity.

Ban 'await' as an identifier in 'using'

---

spec.emu

This adds the `IsUsingDeclaration` SDO, which is currently missing from the proposal specification text.

Add the missing `IsUsingDeclaration` SDO

---

spec.emu

This adds a `DisposeCapability` Record type to sit between `DisposableStack` Objects/Environment Records and the disposable resource stack they hold for more consistent argument passing to the `AddDisposableResource` and `DisposeResources` AOs.
Discussed here: https://github.com/rbuckton/ecma262/pull/2/files#r1086923518

Add DisposeCapability Record

---

spec.emu

Per editor feedback in https://github.com/tc39/proposal-async-explicit-resource-management/issues/9, this moves the _BindingPattern_ restriction for `using` declarations to an Early Error to avoid ambiguity from using the `Using` parameter in two different ways. The early error condition is roughly equivalent to how `const` declarations report an early error on a missing _Initializer_.

Move BindingPattern restriction for 'using' to an early error

---

spec.emu

This simplifies `DisposableStack.prototype.use` to use the existing logic in `AddDisposableResource` handle retrieving the `Symbol.dispose` method. This is pretty much the same change I made in https://tc39.es/proposal-async-explicit-resource-management/#sec-disposablestack.prototype.use.

Streamline DisposableStack.prototype.use

---

spec.emu

This reverts #145 by switching back to a production parameter to restrict _BindingPattern_ in a _UsingDeclaration_. Relying only on an early error would result in a conflict when parsing `using[x]`, which was not intended.
This also addresses editor feedback from https://github.com/tc39/proposal-async-explicit-resource-management/issues/9 by ensuring that we're not giving the `Using` production parameter two different meanings.

Switch back to a production parameter

---

spec.emu

This AO is only ever called with a value and no method, or, with an undefined value and a method.
Another alternative, which might be cleaner, is making both method and value optional, and add an assertion that only one, not both, are present.

[spec] clean up AddDisposableResource

---

spec.emu

Per March 2023 plenary consensus, this reverts the `await` identifier restriction in `using`.

Revert 'await' restriction

---

spec.emu

This amends the `AddDisposableResource` and `CreateDisposableResource` AOs with text from the Async Explicit Resource Management proposal that was missed in #154.
- https://tc39.es/proposal-async-explicit-resource-management/#sec-adddisposableresource-disposable-v-hint-disposemethod &ndash; Steps 1.a-b replace Steps 1.a-c
- https://tc39.es/proposal-async-explicit-resource-management/#sec-createdisposableresource &ndash; Steps 1.a-b replace Steps 1.a-c
These were changes that were made to satisfy the constraint that an `await using` that is evaluated forces an implicit `await` at the end of the block, even if the initializers were `null` or `undefined`.

Fix missing text from async spec

---

spec.emu

This adds entries that were missing that are necessary to describe the behavior of the `.prototype` property on the `DisposableStack` and `AsyncDisposableStack` constructors.
cc: @tc39/ecma262-editors

Add missing .prototype property entries for DisposableStack/AsyncDisposableStack

---

spec.emu

This adds missing calls to `NewDisposeCapability()` in the `NewFunctionEnvironment()` and `NewModuleEnvironment()` AOs
Fixes #170
Fixes #173
cc: @tc39/ecma262-editors

Add missing calls to NewDisposeCapability AOs

---

spec.emu

This moves the `DisposeResources` calls from the abstract closures in `EvaluateFunctionBody`, `GeneratorStart`, `AsyncGeneratorStart`, and `AsyncBlockStart` to the `Evaluation` of `FunctionStatementList`. This centralizes the disposal logic for all function types and avoids the complexity of handling functions created from Abstract Closures that do not currently establish a proper declarative environment.
This change is based on findings discovered while writing Test262 tests and implementing this proposal in Engine262.
Fixes #176
Fixes #177
cc: @tc39/ecma262-editors

Move DisposeResources to Evaluation of FunctionStatementList

---

spec.emu

This updates the proposal specification to use the most recent specification text from https://github.com/tc39/ecma262.

Update to latest version of ECMA-262

---

spec.emu

This updates the algorithm text for `DisposableStack.prototype.adopt` to align with `AsyncDisposableStack.prototype.adopt` and the much of the rest of ECMA-262 which now uses an Abstract Closure passed to `CreateBuiltinFunction` instead of a separate set of steps.
NOTE: This is intended to be purely an editorial change with no normative impact.

Update DisposableStack.p.adopt to use an Abstract Closure

---

spec.emu

PR #180 reached consensus in the July, 2023 TC39 plenary, but there was a typo in the `GetDisposeMethod` AO that results a normative change that was not intentional nor part of the consensus. It has long been the intent that we should throw early when `@@asyncDispose` or `@@dispose` is not found on a resource, but #180 inadvertently lost this requirement. This PR intends to align the proposal text with the actual consensus.
A PR against ecma262 is being tracked in https://github.com/rbuckton/ecma262/pull/5.
Fixes #208

Fix `GetDisposeMethod` to match consensus

---

spec.emu

The `DisposeResources` AO fails to indicate that the resources in its `[[DisposableResourceStack]]` slot will no longer be used and can be freed. As a result, a `DisposableStack` will inadvertently hold resources in memory until the `DisposableStack` instance is freed, which is not an intended behavior.
This changes `DisposeResources` to set the `[[DisposableResourceStack]]` to a new empty list, along with a NOTE indicating the resources can be freed.
A PR against ecma262 is being tracked by https://github.com/rbuckton/ecma262/pull/8.
Fixes #191
/cc: @tc39/ecma262-editors

Fix `DisposeCapability` leak

---

spec.emu

Per discussion in https://github.com/tc39/proposal-explicit-resource-management/pull/216#issuecomment-2015449095, this adds a `PromiseCapability` to the wrapper function created around a `@@dispose` method read by an `await using` declaration to ensure that any errors thrown by `@@dispose` are not thrown synchronously. This is in keeping with the mechanism used in `%AsyncFromSyncIteratorPrototype%.next()`.

Add PromiseCapability wrapper around sync dispose used in an `await using`

---

spec.emu

This fixes a missing lookahead restriction to prevent `export await using` like we do for `export using` that was overlooked when we chose `await using` over `using await`.
The PR against ecma262 is being tracked in https://github.com/rbuckton/ecma262/pull/4

Fix missing lookahead restriction
